' userdefined excitation function 

Option Explicit

Function ExcitationFunction(dtime As Double) As Double

   'Assign the excitation signal value for the given time to the function name.

   ExcitationFunction = 0.0

End Function

' -------------------------------------------------------------------------------------------------
' Main: This function serves as a main program for testing purposes. (runs and plots the function)
'       You need to rename this function to "Main" for debugging the excitation function.
'
'       Please adjust the time step width and the number of time steps accordingly.
'
'		PLEASE NOTE that a userdefined excitation file (*.usf) must not contain a main program for
'       proper execution by the framework. Therefore please ensure to rename this function
'       to e.g. "Main2" before the Transient Solver is started
' -------------------------------------------------------------------------------------------------

Sub Main2
	Dim tmax As Double, ntstep As Long

	' -------------- PLEASE ADJUST THE SETTINGS BELOW ----------------------
	tmax   = 10.0
	ntstep = 100
	' -------------- PLEASE ADJUST THE SETTINGS ABOVE ----------------------

	Dim signal As Object, n As Long, tstep As Double
	Set signal = Result1D("")
	signal.Initialize ntstep
	tstep = tmax / ntstep

	For n=0 To ntstep-1
		signal.SetXY(n, n * tstep, ExcitationFunction(n * tstep))
	Next n

	signal.Save GetProjectBaseName() + GetProjectBaseNameSeparator() + "excitation function.sig"
	signal.AddToTree "Excitation Signals\Userdefined Functions\signal2_plot"
	SelectTreeItem  "Excitation Signals\Userdefined Functions\signal2_plot"
	ResultTree.RefreshView
End Sub
